# Создание своего исключения

Чтобы создать свое исключение, нужно добавить новый класс и унаследоваться от существующего класса исключения. "Проверяемость" исключения наследуется, т-е если унаследоваться от RuntimeException, то исключение будет непроверяемое. Если от Exception - то проверяемое.

При объявлении своего исключения делаем два конструктора:

```java
class MyRtException extends RuntimeException {   // Создали непроверяемое исключение
    
    public MyRtException() { }
    
    public MyRtException(String message) {
        super(message);
    }
    
}
```

# Выброс, оператор throw

Для выброса исключения используется оператор `throw`. Выбрасывать можно двумя способами:

* Создать объект исключения заранее:

  ```java
  var exc = new MyRtException("Тестовая ошибка");  // <-- Создали заранее и положили в переменную
  try {
      throw exc;  // <-- Выбросили когда потребовалось
  }
  catch (Exception ex) {
      System.out.println(ex.getMessage());
  }
  ```

* Создать объект исключения непосредственно в момент выброса:

  ```java
  try {
      throw new MyRtException("Палата №6");  // <-- Создали и сразу выбросили
  }
  catch (Exception ex) {
      System.out.println(ex.getMessage());
  }
  ```

## Правило выброса

> Потомок не должен выбрасывать более общие исключения, чем родитель. 

Иначе нельзя будет безопасно использовать объект потомка вместо родителя. Если клиентский код ориент

Если клиентский код ориентирован на отлов исключения, которое были в родителе, он не среагирует на более общее исключение, выброшенное потомком.

Пример:

```java
class SpecificException extends RuntimeException { }
```

```java
class Parent {
    public void method() {
        throw new SpecificException();
    }
}
```

```java
class Child extends Parent {
    @Override
    public void method() {
        throw new RuntimeException();  // Потомок выбрасывает более общее исключение
    }
}
```

```java
public static void main(String[] args) {

    boolean works = false;
    Parent a = works ? new Parent() : new Child();

    try {
        a.method();
    } catch (SpecificException ex) {
        System.out.println("Поймали исключение.");
    }
    System.out.println("main() ends");

}
```

Когда в переменной `a` лежит объект Parent, то программа работает, а когда Child - нет. Потому что Child выбросит RuntimeException, и оператор catch, рассчитанный на более специфичное SpecificException, на него не среагирует.

# Перехват, оператор catch

## Правило перехвата

> Сначала ловим более специфичные исключения, потом - более общие.

Если сначала ловить более общие, то до специфичных дело не дойдет. Это правило поддерживается на уровне компилятора и поэтому нарушить его по сути невозможно:

```java
try {
    throw new MyRtExceptionB();
}
catch (Exception ex) {
    System.out.println("Поймал исключение типа Exception");
}
catch (MyRtExceptionB ex) {  // Ошибка компиляции, т.к. сюда попасть невозможно
    System.out.println("Поймал исключение типа MyRtExceptionB");
}
```

Дополнительная фишка - если компилятор видит попытку поймать исключение, которое не может возникнуть, он тоже не компилирует:

```java
try {
    throw new MyRtExceptionB();
}
catch (MyExceptionA ex) {  // Ошибка компиляции, такое исключение не может возникнуть
    System.out.println("Поймал исключение типа MyExceptionA");
}
catch (Exception ex) {
    System.out.println("Поймал исключение типа Exception");
}
```



## Совмещенный обработчик

Если для двух видов исключений требуется одинаковая обработка, можно совместить их в одном блоке *catch* (доступно с Java 7):

```java
try {
    if (args[0].length() > args[1].length())
        throw new FileNotFoundException();
    else
        throw new UnknownHostException();
}
catch (FileNotFoundException | UnknownHostException ex) {
    System.out.println("Поймал исключение, а толку?");
}
```

Таким образом можно ловить исключения только в случае, когда одно не является потомком другого. Оба исключения из примера являются потомками *IOException*, поэтому все нормально. Но написать например `catch (Exception | UnknownHostException ex)` нельзя, была бы ошибка *Types in multi-catch must be disjoint: 'java.net.UnknownHostException' is a subclass of 'java.lang.Exception'*.

# Оператор throws в заголовке метода

При объявлении метода можно указать список исключений, которые в нем могут возникнуть. Делается это оператором `throws`.

```java
class MyChecked extends Exception {  }  // Проверяемое
class MyUnchecked extends RuntimeException {  }  // Непроверяемое
```

```java
class Bar {
    
    // В конструкторах тоже можно указывать возможные исключения
    public Bar() throws IOException {

    }

    // через throws указываем потенциальные исключения, которые может выбросить метод
    public void methodA() throws MyChecked {
        throw new MyChecked();  // Ok, хотя нет обработчика, но есть throws
    }

    public void methodB() {
        throw new MyChecked();  // Ошибка компиляции, нет ни throws, ни обработчика
    }

    public void methodC() throws MyUnchecked {  // throws бесполезен для непроверяемых
        throw new MyUnchecked();
    }
    
}
```

```java
public class Main {
    public static void main(String[] args) {
        Bar bar = new Bar();  // Ошибка компиляции, т-к не ловим проверяемое IOException
        bar.methodA();  // Ошибка компиляции, т-к не обрабатываем проверяемое исключение
        bar.methodC();  // Ok, потому что компилятор не следит за непроверяемыми исключениями
    }
}
```

Ошибка тут будет только из-за *IOException* и *MyChecked*, потому что оно проверяемое (т-к наследуется от *Exception*). На *MyUnchecked* компилятор ругаться не будет, потому что оно непроверяемое (т-к наследуется от *RuntimeException*).

Отсюда вывод, что с *технической точки зрения* в throws имеет смысл указывать только исключения, относящиеся к проверяемым. В случае непроверяемых throws бесполезен и ни на что не влияет.

Оператор throws в основном нужен для того, чтобы помечать собственные методы, в которых может возникнуть *IOException* (или другое проверяемое исключение), но обработку хочется делегировать клиентскому коду.

Есть даже такое правило - "выбрасывать исключения надо как можно раньше, а обрабатывать как можно позже". Потому что методы-работяги должны работать и только сообщать о проблемах, а думать как эти проблемы решить должен высокоуровневый клиентский код.

Допустим, мы в методе хотим читать из файла с помощью объекта *FileWriter*:

```java
import java.io.FileWriter;
...
public void methodB() {
    FileWriter writer = new FileWriter("notes3.txt", false);  // Ошибка компиляции тут
}
...
.methodB();
```

Если написать так, то не скомпилируется (ошибка *Unhandled exception: java.io.IOException*), потому что мы не обрабатываем потенциальные IO-ошибки. Но если подписать throws:

```java
import java.io.FileWriter;
...
public void methodB() throws IOException {  // <-- Добавили throws
    FileWriter writer = new FileWriter("notes3.txt", false);
}
...
.methodB();  // Ошибка компиляции теперь тут
```

То ошибка компиляции уйдет из непосредственно самого метода в место его вызова. Т-е мы таким образом делегируем обработку потенциального исключения клиентскому коду.