# Повторная генерация

Повторный выброс делается так:

```java
try {
    ...     
}
catch (Exception ex) {
    throw ex;
}
```

# Цепочка исключений

Цепочка формируется куда удобнее, чем в C#:

```java
try {
    try {
        throw new MyRtExceptionB("Что-то пошло не так");
    }
    catch (Exception ex) {
        MyRtExceptionB reason = new MyRtExceptionB("Демонстрация цепочек исключения");
        reason.initCause(ex);  // <-- В новое исключение добавляем исходную причину
        throw reason;
    }
}
catch (Exception ex) {
    Throwable cause = ex.getCause();  // <-- Получаем причину пойманного исключения
    System.out.println(cause.getMessage());
    System.out.println(ex.getMessage());
    ex.printStackTrace();
}

// Вывод
Что-то пошло не так
Демонстрация цепочек исключения
com.company.sampleprog.MyRtExceptionB: Демонстрация цепочек исключения
	at com.company.sampleprog.Main.main(Main.java:17)
Caused by: com.company.sampleprog.MyRtExceptionB: Что-то пошло не так
	at com.company.sampleprog.Main.main(Main.java:14)
```

